### ISSUE TITLE
The app gets stucked in the splash screen

### ISSUE THREAD

**Issue by FranciselMudo** [ThisIsSidam/rem-reminds-you#9]
Version 1.0.0 beta 4 of the app. Running android 14 on a pixel 7. 
[file.txt](https://github.com/user-attachments/files/16645616/file.txt)

**Comment by ThisIsSidam** [comment]
@FranciselMudo I checked the logs. It is as I have previously mentioned, happening because the application is not able to handle reminders of previous version. 

Install the previous version, and remove all reminders, both from homepage and archive and then uninstall, and install the new version. It should work then.

**Comment by ThisIsSidam** [comment]
The issue occurs because the reminders from previous version are not properly deleted upon uninstall (v1.0.0-beta.4 and prior version do not support reminders from previous version). Why do the reminders stay even after uninstall? Don't know. 

Well, the problem was solved when the bug reporter "force closed the app, then deleted cache and storage, and restarted my device".
